# Generated by Django 4.2.1 on 2026-03-30 05:12

import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_library_domain(apps, schema_editor):
    Bookinventory = apps.get_model("core", "Bookinventory")
    BookCopy = apps.get_model("core", "BookCopy")
    LibraryProfile = apps.get_model("core", "LibraryProfile")
    Loan = apps.get_model("core", "Loan")
    Log = apps.get_model("core", "Log")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    for user in User.objects.all():
        LibraryProfile.objects.get_or_create(
            user=user,
            defaults={
                "role": "patron",
                "card_number": f"CARD-{user.pk:06d}",
            },
        )

    for book in Bookinventory.objects.all():
        search_document = " ".join(
            part
            for part in [
                book.title,
                getattr(book, "subtitle", ""),
                book.author,
                book.publisher,
                book.isbn,
                getattr(book, "genre", ""),
                getattr(book, "language", ""),
                getattr(book, "audience", ""),
                book.description,
                getattr(book, "summary", ""),
            ]
            if part
        )
        if book.search_document != search_document:
            book.search_document = search_document
            book.save(update_fields=["search_document"])

        existing_count = BookCopy.objects.filter(inventory=book).count()
        for index in range(existing_count + 1, book.quantity + 1):
            BookCopy.objects.create(
                inventory=book,
                barcode=f"LIB-{book.isbn}-{index:04d}",
            )

    for log in Log.objects.filter(returned_date__isnull=True, loan__isnull=True).order_by("id"):
        if not log.book_id:
            continue
        available_copy = BookCopy.objects.filter(
            inventory_id=log.book_id,
            status="available",
        ).order_by("barcode").first()
        if not available_copy:
            continue

        borrower = User.objects.filter(email=log.borrower_email).first()
        checked_out_at = django.utils.timezone.make_aware(
            datetime.datetime.combine(log.borrowed_date, log.borrowed_time)
        )
        due_at = checked_out_at + datetime.timedelta(days=21)
        loan = Loan.objects.create(
            inventory_id=log.book_id,
            copy=available_copy,
            borrower=borrower,
            processed_by=None,
            borrower_email_snapshot=log.borrower_email,
            checked_out_at=checked_out_at,
            due_at=due_at,
            status="active",
        )
        available_copy.status = "on_loan"
        available_copy.due_back_date = due_at.date()
        available_copy.save(update_fields=["status", "due_back_date"])
        log.loan = loan
        log.save(update_fields=["loan"])


def create_sqlite_fts(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return

    schema_editor.execute(
        """
        CREATE VIRTUAL TABLE IF NOT EXISTS bookinventory_fts USING fts5(
            title,
            subtitle,
            author,
            publisher,
            isbn,
            genre,
            description,
            summary,
            search_document,
            content='bookinventory',
            content_rowid='id'
        )
        """
    )
    schema_editor.execute(
        """
        INSERT INTO bookinventory_fts(rowid, title, subtitle, author, publisher, isbn, genre, description, summary, search_document)
        SELECT id, title, subtitle, author, publisher, isbn, genre, description, summary, search_document
        FROM bookinventory
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER IF NOT EXISTS bookinventory_ai AFTER INSERT ON bookinventory BEGIN
            INSERT INTO bookinventory_fts(rowid, title, subtitle, author, publisher, isbn, genre, description, summary, search_document)
            VALUES (new.id, new.title, new.subtitle, new.author, new.publisher, new.isbn, new.genre, new.description, new.summary, new.search_document);
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER IF NOT EXISTS bookinventory_ad AFTER DELETE ON bookinventory BEGIN
            INSERT INTO bookinventory_fts(bookinventory_fts, rowid, title, subtitle, author, publisher, isbn, genre, description, summary, search_document)
            VALUES ('delete', old.id, old.title, old.subtitle, old.author, old.publisher, old.isbn, old.genre, old.description, old.summary, old.search_document);
        END
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER IF NOT EXISTS bookinventory_au AFTER UPDATE ON bookinventory BEGIN
            INSERT INTO bookinventory_fts(bookinventory_fts, rowid, title, subtitle, author, publisher, isbn, genre, description, summary, search_document)
            VALUES ('delete', old.id, old.title, old.subtitle, old.author, old.publisher, old.isbn, old.genre, old.description, old.summary, old.search_document);
            INSERT INTO bookinventory_fts(rowid, title, subtitle, author, publisher, isbn, genre, description, summary, search_document)
            VALUES (new.id, new.title, new.subtitle, new.author, new.publisher, new.isbn, new.genre, new.description, new.summary, new.search_document);
        END
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_reconcile_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On Loan"),
                            ("on_hold", "On Hold"),
                            ("maintenance", "Maintenance"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=32,
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("condition_notes", models.TextField(blank=True, default="")),
                (
                    "due_back_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("last_circulated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["barcode"],
                "permissions": [
                    ("manage_inventory", "Can manage inventory and copies")
                ],
            },
        ),
        migrations.CreateModel(
            name="HoldRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready for Pickup"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["requested_at"],
                "permissions": [("approve_holds", "Can approve and fulfill holds")],
            },
        ),
        migrations.CreateModel(
            name="LibraryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patron", "Patron"),
                            ("librarian", "Librarian"),
                            ("curator", "Curator"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="patron",
                        max_length=32,
                    ),
                ),
                ("card_number", models.CharField(max_length=32, unique=True)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("max_active_loans", models.PositiveIntegerField(default=5)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower_email_snapshot", models.EmailField(max_length=255)),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("due_at", models.DateTimeField(db_index=True)),
                (
                    "returned_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_out_at"],
                "permissions": [("manage_loans", "Can check books in and out")],
            },
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="audience",
            field=models.CharField(
                blank=True, db_index=True, default="General", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="genre",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="language",
            field=models.CharField(
                blank=True, db_index=True, default="English", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="search_document",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="shelf_location",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="author",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="available_quantity",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="isbn",
            field=models.CharField(db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="published_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="publisher",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="log",
            name="borrowed_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="borrower_email",
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="log",
            name="isbn",
            field=models.CharField(db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name="log",
            name="returned_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["title"], name="book_title_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["author"], name="book_author_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["publisher"], name="book_publisher_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["isbn"], name="book_isbn_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["published_date"], name="book_pubdate_idx"),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(
                fields=["available_quantity"], name="book_available_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookinventory",
            index=models.Index(fields=["genre", "audience"], name="book_genre_aud_idx"),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["isbn", "returned_date"], name="log_isbn_returned_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["borrower_email", "borrowed_date"], name="log_borrower_date_idx"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="core.bookcopy",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="core.bookinventory",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="libraryprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holdrequest",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holds",
                to="core.bookinventory",
            ),
        ),
        migrations.AddField(
            model_name="holdrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hold_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="core.bookinventory",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_logs",
                to="core.loan",
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["inventory", "status"], name="loan_inventory_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["borrower", "status"], name="loan_borrower_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["due_at", "status"], name="loan_due_status_idx"),
        ),
        migrations.AddIndex(
            model_name="holdrequest",
            index=models.Index(
                fields=["inventory", "status"], name="hold_inventory_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holdrequest",
            index=models.Index(
                fields=["requester", "status"], name="hold_requester_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["inventory", "status"], name="copy_inventory_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["status", "due_back_date"], name="copy_status_due_idx"
            ),
        ),
        migrations.RunPython(backfill_library_domain, migrations.RunPython.noop),
        migrations.RunPython(create_sqlite_fts, migrations.RunPython.noop),
    ]
